version: "3"
services:
  reverseproxy:
    build:
      context: ../reverse-proxy
    image: sinclaireric60/udagram-reverse-proxy
  backend_user:
    build:
      context: ../udagram-api-user
    image: sinclaireric60/udagram-api-user
  backend_feed:
    build:
      context: ../udagram-api-feed
    image: sinclaireric60/udagram-api-feed
  frontend:
    build:
      context: ../udagram-frontend
    image: sinclaireric60/udagram-frontend